#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=htpc-manager

# The parameter $1 is the backup directory location
	backup_dir="$1/apps/$app"
	sudo mkdir -p $backup_dir

# Backup files
	# Backup sources
	sudo cp -a /opt/yunohost/$app/. $backup_dir/sources

	# Backup data
	sudo cp -a /home/yunohost.app/$app/. $backup_dir/data
	
	# Backup daemon config
	sudo cp -a /etc/systemd/system/$app.service $backup_dir/conf/$app.service


# Copy Nginx and YunoHost parameters to make the script "standalone"
	sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
	domain=$(sudo yunohost app setting $app domain)
	sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf