#!/bin/bash

app=htpc-manager

# Retrieve arguments
	domain=$1
	path=$2

# Find an unused port
	port=8089
	sudo yunohost app checkport $port
	while [[ ! $? -eq 0 ]]
	do
		port=$(($port + 1))
		sudo yunohost app checkport $port
	done
	sudo yunohost app setting $app port -v "$port"

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Check domain/path availability
	sudo yunohost app checkurl $domain$path -a $app \
		|| (echo "Path not available: $domain$path" && exit 1)

# Install dependencies
	sudo apt-get install -y -qq build-essential git python-imaging python-dev python-setuptools python-pip python-cherrypy vnstat
	sudo pip install psutil

# Copy source files
	data_path=/home/yunohost.app/$app
	final_path=/opt/yunohost/$app
	sudo mkdir -p $data_path
	sudo mkdir -p $final_path
	sudo cp -a ../sources/. $final_path

# Create app user and set permissions
	id -u $app &>/dev/null || sudo useradd --home-dir $data_path --shell /bin/false $app
	
# Configure daemon
	sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/$app.service
	sudo sed -i "s@PORTTOCHANGE@$port@g" ../conf/$app.service
	sudo cp -a ../conf/$app.service /etc/systemd/system/
	sudo systemctl daemon-reload
	sudo systemctl enable $app.service
	
# Redirect log file
	log_path=/var/log/$app
	sudo mkdir -p $log_path
	sudo chown -R $app $log_path
	sudo chmod +x -R $log_path
	sudo sed -i "s@self.logfile =.*@self.logfile = '$log_path/$app.log'@g" $final_path/htpc/log.py
	
# Set rights
	sudo chown -R $app $final_path
	sudo chown -R $app $data_path
	sudo chmod +x -R $final_path
	sudo chmod +x -R $data_path
	
# Add service to YunoHost's monitoring
	sudo yunohost service add $app --log $log_path --status "ps aux | grep $app | grep -v grep"
	
# Start service
	sudo service $app start

# Nginx
	sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
	sed -i "s@PROXYTOCHANGE@http://127.0.0.1:${port}${path%/}@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
	sudo service nginx reload
	sudo yunohost app ssowatconf
