#!/bin/bash
app=htpc-manager

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)

# Remove init script
	sudo service $app stop
	sudo systemctl disable $app.service
	sudo rm -rf /etc/systemd/system/$app.service
	sudo systemctl daemon-reload
	
# Delete app user
	sudo deluser $app
	
# Remove sources
	sudo rm -rf /opt/yunohost/$app

# Remove logs
	sudo rm -rf /var/log/$app

# Remove data
	sudo rm -rf /home/yunohost.app/$app

# Remove configuration files
	sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove Yunohost service
	sudo yunohost service remove $app

# Reload Nginx and update Yunohost
	sudo service nginx reload
	sudo yunohost app ssowatconf