#!/bin/bash
app=htpc-manager

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)

# Kill app and remove from boot
	sudo service $app stop
	sudo killall $app
	sudo update-rc.d $app remove
	
# Delete app user
	sudo deluser $app
	
# Remove sources
	sudo rm -rf /opt/yunohost/$app

# Remove logs
	sudo rm -rf /var/log/$app

# Remove data
	sudo rm -rf /home/yunohost.app/$app
	
# Remove daemon config
	sudo rm -f /etc/init.d/$app
	sudo rm -f /etc/default/$app
	sudo rm -rf /var/run/$app

# Remove configuration files
	sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove Yunohost service
	sudo yunohost service remove $app

# Reload Nginx and update Yunohost
	sudo service nginx reload
	sudo yunohost app ssowatconf