#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=htpc-manager

# The parameter $1 is the uncompressed restore directory location
	backup_dir=$1/apps/$app

# Restore files
	# Kill app
	sudo service $app stop
	sudo killall $app

	# Restore sources
	sudo cp -a $backup_dir/sources/. /opt/yunohost/$app

	# Restore data
	sudo cp -a $backup_dir/data/. /home/yunohost.app/$app
	
	# Restore daemon config
	sudo cp -a $backup_dir/conf/$app.service /etc/systemd/system/$app.service
	
	# Set rights
	sudo chown -R $app /opt/yunohost/$app
	sudo chown -R $app /home/yunohost.app/$app
	sudo chmod +x -R /opt/yunohost/$app
	sudo chmod +x -R /home/yunohost.app/$app
	
	# Start daemon at boot
	sudo systemctl daemon-reload
	sudo systemctl enable $app.service

# Restore Nginx and YunoHost parameters
	sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
	domain=$(sudo yunohost app setting $app domain)
	sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
	sudo service nginx reload
	sudo yunohost app ssowatconf