#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=htpc-manager

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)
	port=$(sudo yunohost app setting $app port)
	
# Kill app
	sudo service $app stop
	sudo killall $app

# Copy source files
	data_path=/home/yunohost.app/$app
	final_path=/opt/yunohost/$app
	sudo mkdir -p $data_path
	sudo mkdir -p $final_path
	sudo cp -a ../sources/. $final_path

# Update daemon
	sudo cp -a ../conf/htpc-manager.init /etc/init.d/$app
	
# Redirect log file
	log_path=/var/log/$app
	sudo mkdir -p $log_path
	sudo chown -R $app $log_path
	sudo chmod +x -R $log_path
	sudo sed -i "s@self.logfile =.*@self.logfile = '$log_path/$app.log'@g" $final_path/htpc/log.py
	
# Set rights
	sudo chown -R $app $final_path
	sudo chown -R $app $data_path
	sudo chmod +x /etc/init.d/$app
	sudo chmod +x -R $final_path
	sudo chmod +x -R $data_path
	
# Start service
	sudo service $app start

# Remove trailing "/" for next commands
	path=${app_path%/}

# Nginx
	sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
	sed -i "s@PROXYTOCHANGE@http://127.0.0.1:${port}${path%/}@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
	sudo service nginx reload
	sudo yunohost app ssowatconf
